#!/bin/bash
name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')
weight=$(jq -r '.weight' data.json)
height=$(jq -r '.height' data.json)

echo "$name is of type $type, weighs $(awk "BEGIN {print $weight/10}")kg, and is $(awk "BEGIN {print $height/10}")m tall."
